server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway-service
    
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product # 포워딩할 주소,
          predicates:
            - Path=/product-api/** # 해당 gateway 서버의 /product-api/**로 들어오는 요은 product로 인식하겠다는 조건
          filters:
            - RewritePath=/product-api/(?<segment>.*), /$\{segment}
        - id: order
          uri: lb://order # 포워딩할 주소,
          predicates:
            - Path=/order-api/** # 해당 gateway 서버의 /order-api/**로 들어오는 요은 product로 인식하겠다는 조건
          filters:
            - RewritePath=/order-api/(?<segment>.*), /$\{segment}
        - id: member
          uri: lb://member # 포워딩할 주소,
          predicates:
            - Path=/member-api/** # 해당 gateway 서버의 /member-api/**로 들어오는 요은 product로 인식하겠다는 조건
          filters:
            - RewritePath=/member-api/(?<segment>.*), /$\{segment}